root: true
env:
  browser: true
  es2017: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaVersion: 2020
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
plugins:
  - svelte3
  - '@typescript-eslint'
overrides:
  - files: ['*.svelte']
    processor: 'svelte3/svelte3'
settings:
  'svelte3/typescript':
    typescript:
      project: tsconfig.json
